spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aipms
    username: [YOUR_DB_USERNAME]
    password: [YOUR_DB_PASSWORD]
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: [YOUR_KAKAO_CLIENT_ID]
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - talk_message
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.aipms.domain

  configuration:
    map-underscore-to-camel-case: true

encrypt:
  secret-key: [λ³µνΈν™” ν‚¤]